import sys
import os
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pickle
import argparse

# Ensure ./src can be imported
sys.path.append(os.getcwd())
from src.players.b12705048.deep_cfr_net import RegretNet, PolicyNet

class CFRDataset(Dataset):
    """ Loads the (state, target, mask) triples generated by MCCFR. """
    def __init__(self, data_path):
        with open(data_path, 'rb') as f:
            self.data = pickle.load(f)
            
    def __len__(self):
        return len(self.data)
        
    def __getitem__(self, idx):
        state, target, mask = self.data[idx]
        return state, target, mask

def train_model(model_type, data_path, save_path, epochs, batch_size, lr):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")
    
    if not os.path.exists(data_path):
        print(f"Data file {data_path} not found!")
        return
        
    dataset = CFRDataset(data_path)
    if len(dataset) == 0:
        print(f"Buffer {data_path} is empty!")
        return
        
    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    
    # Initialize appropriate model
    if model_type == "regret":
        model = RegretNet().to(device)
    else:
        model = PolicyNet().to(device)
        
    # Load existing weights if continuing training
    if os.path.exists(save_path):
        try:
            model.load_state_dict(torch.load(save_path, map_location=device))
            print(f"Loaded existing weights from {save_path}")
        except RuntimeError as e:
            print(f"[Warning] Incompatible weights at {save_path}, starting fresh: {e}")
        
    optimizer = optim.Adam(model.parameters(), lr=lr)
    criterion = nn.MSELoss()
    
    model.train()
    for epoch in range(epochs):
        total_loss = 0.0
        for states, targets, masks in dataloader:
            states = states.to(device)
            targets = targets.to(device)
            legal_mask = masks.bool().to(device)
            
            optimizer.zero_grad()
            
            if model_type == "regret":
                predictions = model(states)
            else:
                predictions = model(states, legal_mask)
            
            # Mask out illegal moves from the loss calculation
            # We only care about optimizing predictions for cards we actually hold
            loss = criterion(predictions[legal_mask], targets[legal_mask])
            
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
        print(f"Epoch {epoch+1:02d}/{epochs} | {model_type.capitalize()} Loss: {total_loss/len(dataloader):.6f}")
        
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    torch.save(model.state_dict(), save_path)
    print(f"{model_type.capitalize()} Network saved to {save_path}\n")


def full_deep_cfr_loop(external_iterations=5, games_per_iter=500, data_dir="results/deep_cfr"):
    """
    Orchestrates the full Deep CFR training cycle:
    Generate Data -> Train RegretNet -> Train PolicyNet -> Repeat
    """
    import subprocess
    
    for i in range(external_iterations):
        print(f"\n=========================================")
        print(f"    DEEP CFR ITERATION {i+1}/{external_iterations}")
        print(f"=========================================")
        
        # 1. Generate Data
        print(f"\n>> Step 1: Generating Data via MCCFR ({games_per_iter} games)...")
        # Runs the data generation script with memory limits in mind
        subprocess.run([sys.executable, "scripts/generate_cfr_data.py", "--num_games", str(games_per_iter), "--data_dir", data_dir])
        
        # 2. Train RegretNet
        print("\n>> Step 2: Training Regret Network...")
        train_model(
            model_type="regret",
            data_path=os.path.join(data_dir, "regret_buffer.pkl"),
            save_path="src/players/b12705048/weights/regret_net.pt",
            epochs=10,
            batch_size=64,
            lr=1e-4
        )
        
        # 3. Train PolicyNet
        print(">> Step 3: Training Policy Network...")
        train_model(
            model_type="policy",
            data_path=os.path.join(data_dir, "policy_buffer.pkl"),
            save_path="src/players/b12705048/weights/policy_net.pt",
            epochs=10,
            batch_size=64,
            lr=1e-4
        )

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--loop", action="store_true", help="Run the full Deep CFR generation+training loop")
    parser.add_argument("--iters", type=int, default=5, help="Number of external Deep CFR iterations")
    parser.add_argument("--games_per_iter", type=int, default=500, help="Number of games to generate per iteration")
    parser.add_argument("--data_dir", type=str, default="results/deep_cfr", help="Directory to store the memory-consuming .pkl buffers")
    args = parser.parse_args()
    
    if args.loop:
        full_deep_cfr_loop(args.iters, args.games_per_iter, args.data_dir)
    else:
        # Just train once on whatever data exists in the buffers
        print("--- Training once on existing buffers ---")
        train_model("regret", os.path.join(args.data_dir, "regret_buffer.pkl"), "src/players/b12705048/weights/regret_net.pt", epochs=10, batch_size=64, lr=1e-3)
        train_model("policy", os.path.join(args.data_dir, "policy_buffer.pkl"), "src/players/b12705048/weights/policy_net.pt", epochs=10, batch_size=64, lr=1e-3)
