"""
Deep CFR Training Script.

This script implements the training phase of the Deep CFR pipeline.
It reads (state, target, mask) triples from replay buffers generated by
``generate_cfr_data.py`` and trains the RegretNet and PolicyNet via
supervised learning.

Pipeline Position:
    This is Steps 2–3 of the iterative Deep CFR loop:
        1. generate_cfr_data.py  (produces regret_buffer.pkl, policy_buffer.pkl)
        2. train_cfr.py --regret ← YOU ARE HERE (trains RegretNet)
        3. train_cfr.py --policy ← YOU ARE HERE (trains PolicyNet)
        4. Repeat from Step 1

Training Details:
    - **RegretNet**: Trained with MSE loss against counterfactual regret
      targets. The regret values are unbounded scalars, so MSE is the
      natural choice.
    - **PolicyNet**: Trained with Cross-Entropy loss against strategy
      probability targets. The network outputs raw logits (no Softmax)
      during training to avoid vanishing gradients from double-Softmax.
      Log-Softmax is applied within the loss computation.

    Both networks mask out illegal actions (cards not in hand) during
    loss computation so the optimizer only updates predictions for
    actions the player could actually take.

Usage:
    # Train once on existing buffers:
    python scripts/train_cfr.py

    # Run the full iterative loop (generate + train × N iterations):
    python scripts/train_cfr.py --loop --iters 10 --games_per_iter 1000
"""

import sys
import os
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pickle
import argparse

# Ensure ./src can be imported
sys.path.append(os.getcwd())
from src.players.b12705048.deep_cfr_net import RegretNet, PolicyNet


# =============================================================================
# Dataset
# =============================================================================

class CFRDataset(Dataset):
    """
    PyTorch Dataset wrapping the (state, target, mask) triples from an
    MCCFR replay buffer pickle file.

    Each item contains:
        - state  (torch.Tensor, shape INPUT_DIM):  Encoded game state.
        - target (torch.Tensor, shape 104):  Regret vector or strategy vector.
        - mask   (torch.Tensor, shape 104):  Boolean legal-action mask.
    """

    def __init__(self, data_path):
        """
        Args:
            data_path (str): Path to the ``.pkl`` file produced by
                ``generate_cfr_data.py``.
        """
        with open(data_path, 'rb') as f:
            self.data = pickle.load(f)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        state, target, mask = self.data[idx]
        return state, target, mask


# =============================================================================
# Training Loop
# =============================================================================

def train_model(model_type, data_path, save_path, epochs, batch_size, lr):
    """
    Train either the RegretNet or PolicyNet on a replay buffer.

    Args:
        model_type (str): ``"regret"`` or ``"policy"`` — determines which
            network architecture and loss function to use.
        data_path (str): Path to the pickle replay buffer file.
        save_path (str): Path to save the trained ``.pt`` weight file.
        epochs (int): Number of training epochs.
        batch_size (int): Mini-batch size for the DataLoader.
        lr (float): Learning rate for the Adam optimizer.
    """
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Using device: {device}")

    if not os.path.exists(data_path):
        print(f"Data file {data_path} not found!")
        return

    dataset = CFRDataset(data_path)
    if len(dataset) == 0:
        print(f"Buffer {data_path} is empty!")
        return

    dataloader = DataLoader(dataset, batch_size=batch_size, shuffle=True)

    # Initialize the appropriate network architecture
    if model_type == "regret":
        model = RegretNet().to(device)
    else:
        model = PolicyNet().to(device)

    # Resume from existing weights if available (allows iterative refinement)
    if os.path.exists(save_path):
        try:
            model.load_state_dict(torch.load(save_path, map_location=device))
            print(f"Loaded existing weights from {save_path}")
        except RuntimeError as e:
            print(f"[Warning] Incompatible weights at {save_path}, starting fresh: {e}")

    optimizer = optim.Adam(model.parameters(), lr=lr)

    # MSE loss for regret prediction (unbounded scalar targets)
    criterion = nn.MSELoss()

    model.train()
    for epoch in range(epochs):
        total_loss = 0.0
        for states, targets, masks in dataloader:
            states = states.to(device)
            targets = targets.to(device)
            legal_mask = masks.bool().to(device)

            optimizer.zero_grad()

            if model_type == "regret":
                # RegretNet: MSE loss on legal actions only
                predictions = model(states)
                loss = criterion(predictions[legal_mask], targets[legal_mask])
            else:
                # PolicyNet: Cross-Entropy loss on strategy distributions
                # The network outputs raw logits (no Softmax) to avoid
                # vanishing gradients; log_softmax is applied here instead.
                logits = model(states, legal_mask)
                log_probs = F.log_softmax(logits, dim=-1)
                loss = -torch.sum(targets[legal_mask] * log_probs[legal_mask]) / states.size(0)

            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        print(f"Epoch {epoch+1:02d}/{epochs} | {model_type.capitalize()} Loss: "
              f"{total_loss/len(dataloader):.6f}")

    # Save trained weights
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    torch.save(model.state_dict(), save_path)
    print(f"{model_type.capitalize()} Network saved to {save_path}\n")


# =============================================================================
# Full Deep CFR Loop
# =============================================================================

def full_deep_cfr_loop(external_iterations=5, games_per_iter=500, data_dir="results/deep_cfr"):
    """
    Orchestrate the complete Deep CFR training cycle.

    Each iteration:
        1. Generates MCCFR data using the current RegretNet.
        2. Trains the RegretNet on the new regret buffer.
        3. Trains the PolicyNet on the new policy buffer.
        4. Saves updated weights for the next iteration.

    The RegretNet improves its regret estimates each iteration, producing
    higher-quality strategies for data generation in subsequent rounds.
    The PolicyNet accumulates the average strategy across all iterations,
    converging toward a Nash Equilibrium.

    Args:
        external_iterations (int): Number of generate→train cycles.
        games_per_iter (int): Games to simulate per data generation step.
        data_dir (str): Directory for replay buffer pickle files.
    """
    import subprocess

    for i in range(external_iterations):
        print(f"\n=========================================")
        print(f"    DEEP CFR ITERATION {i+1}/{external_iterations}")
        print(f"=========================================")

        # Step 1: Generate training data via MCCFR traversal
        print(f"\n>> Step 1: Generating Data via MCCFR ({games_per_iter} games)...")
        subprocess.run([
            sys.executable, "scripts/generate_cfr_data.py",
            "--num_games", str(games_per_iter),
            "--data_dir", data_dir
        ])

        # Step 2: Train RegretNet on counterfactual regret targets
        print("\n>> Step 2: Training Regret Network...")
        train_model(
            model_type="regret",
            data_path=os.path.join(data_dir, "regret_buffer.pkl"),
            save_path="src/players/b12705048/weights/regret_net.pt",
            epochs=10,
            batch_size=64,
            lr=1e-4
        )

        # Step 3: Train PolicyNet on strategy distribution targets
        print(">> Step 3: Training Policy Network...")
        train_model(
            model_type="policy",
            data_path=os.path.join(data_dir, "policy_buffer.pkl"),
            save_path="src/players/b12705048/weights/policy_net.pt",
            epochs=10,
            batch_size=64,
            lr=1e-4
        )


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description="Train Deep CFR networks from MCCFR replay buffers."
    )
    parser.add_argument("--loop", action="store_true",
                        help="Run the full Deep CFR generation+training loop")
    parser.add_argument("--iters", type=int, default=5,
                        help="Number of external Deep CFR iterations")
    parser.add_argument("--pretrain", action="store_true",
                        help="Run FlatMCO1 imitation pre-training before the deep CFR loop")
    parser.add_argument("--pretrain_games", type=int, default=200,
                        help="Number of games to use for pre-training")
    parser.add_argument("--games_per_iter", type=int, default=500,
                        help="Number of games to generate per iteration")
    parser.add_argument("--data_dir", type=str, default="results/deep_cfr",
                        help="Directory to store replay buffer .pkl files")
    args = parser.parse_args()

    if args.pretrain:
        print("=== Running FlatMCO1 Imitation Pre-Training ===")
        import scripts.pretrain_from_flatmc as pretrain
        pretrain.generate_and_train(num_games=args.pretrain_games)

    if args.loop:
        full_deep_cfr_loop(args.iters, args.games_per_iter, args.data_dir)
    else:
        # One-shot training on existing buffers (useful for debugging)
        print("--- Training once on existing buffers ---")
        train_model("regret",
                     os.path.join(args.data_dir, "regret_buffer.pkl"),
                     "src/players/b12705048/weights/regret_net.pt",
                     epochs=10, batch_size=64, lr=1e-3)
        train_model("policy",
                     os.path.join(args.data_dir, "policy_buffer.pkl"),
                     "src/players/b12705048/weights/policy_net.pt",
                     epochs=10, batch_size=64, lr=1e-3)
